### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by adacom72** [ZhangTianrong/scoop-bucket#1]
not an issue just a request for help - how do i run the code in the scoop bucket - non of the methods for auto loading the disable rounded corners work for me  - i installed explorer patcher and then uninstalled it and that seems to have screwed things up - how i have no idea but on another laptop other methods suggested here work fine - they have not had explorer patcher so i am assuming thats the problem on this laptop

**Comment by ZhangTianrong** [comment]
This is not directly relevant to the scoop bucket and seems to have been handled [here](https://github.com/oberrich/win11-toggle-rounded-corners/issues/15#issuecomment-1814826500) already. It's said that the scheduled task installed with `schtasks` may not work for laptops because it cannot remove the condition that AC power must be connected from the task, but by importing a task from xml like here should have avoided that problem and I have tested the task installer script on a laptop and didn't encounter any problem.

As to how to use the scoop bucket, just read the readme file. Regarding explorer patcher, I have got that installed once too and that doesn't cause an issue with `win11-toggle-rounded-corners`. If you have more question, please follow up in the repo of `win11-toggle-rounded-corners`.
